# Generated by Django 2.1.7 on 2019-10-09 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('files', '0001_initial'),
        ('bank_guarantee', '0002_auto_20191009_0932'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_request', '0002_requesttender_placement'),
        ('cabinet', '0002_auto_20191009_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_request.BankDocumentType'),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.Certificate'),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.BaseFile'),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='print_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_guarantee.RequestPrintForm'),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_guarantee.Request'),
        ),
        migrations.AddField(
            model_name='request',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Agent', verbose_name='Агент'),
        ),
        migrations.AddField(
            model_name='request',
            name='agent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оператор агента'),
        ),
        migrations.AddField(
            model_name='request',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Bank'),
        ),
        migrations.AddField(
            model_name='request',
            name='base_request',
            field=models.ForeignKey(blank=True, help_text='Заявка, с которой была скопирована текущая заявка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_guarantee.Request', verbose_name='Базовая заявка'),
        ),
        migrations.AddField(
            model_name='request',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_guarantee.RequestStatus', verbose_name='Текущий статус'),
        ),
        migrations.AddField(
            model_name='request',
            name='tender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_request.RequestTender', verbose_name='Конкурс'),
        ),
        migrations.AddField(
            model_name='offertemplatedocument',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.BaseFile'),
        ),
        migrations.AddField(
            model_name='offertemplatedocument',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_guarantee.Offer'),
        ),
        migrations.AddField(
            model_name='offertemplatedocument',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_guarantee.OfferTemplate'),
        ),
        migrations.AddField(
            model_name='offertemplate',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Bank'),
        ),
        migrations.AddField(
            model_name='offerprintform',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Bank'),
        ),
        migrations.AddField(
            model_name='offerdocument',
            name='bank_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_offers_signs', to='cabinet.Certificate'),
        ),
        migrations.AddField(
            model_name='offerdocument',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank_guarantee.OfferDocumentCategory'),
        ),
        migrations.AddField(
            model_name='offerdocument',
            name='client_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_offers_signs', to='cabinet.Certificate'),
        ),
        migrations.AddField(
            model_name='offerdocument',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.BaseFile'),
        ),
        migrations.AddField(
            model_name='offerdocument',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_guarantee.Offer'),
        ),
        migrations.AddField(
            model_name='offerdocument',
            name='print_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank_guarantee.OfferPrintForm'),
        ),
        migrations.AddField(
            model_name='offer',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Bank', verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='offer',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='bank_guarantee.Request', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='messagefile',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.Certificate'),
        ),
        migrations.AddField(
            model_name='messagefile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.BaseFile'),
        ),
        migrations.AddField(
            model_name='messagefile',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_guarantee.Message'),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='discuss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_guarantee.Discuss'),
        ),
        migrations.AddField(
            model_name='externalrequest',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Bank'),
        ),
        migrations.AddField(
            model_name='externalrequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_guarantee.Request'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Agent'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Bank'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_guarantee.Request'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_request.BankDocumentType'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.BaseFile'),
        ),
        migrations.AddField(
            model_name='bankofferdocumentcategory',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Bank'),
        ),
        migrations.AddField(
            model_name='bankofferdocumentcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_guarantee.OfferDocumentCategory'),
        ),
    ]
