# Generated by Django 2.1.7 on 2019-10-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0003_auto_20191009_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestprintform',
            name='filename',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Шаблон формы, если есть'),
        ),
    ]
