# Generated by Django 2.1.7 on 2019-10-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0004_auto_20191009_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestprintform',
            name='type',
            field=models.CharField(choices=[('', ''), ('BG', 'bank_guarantee'), ('LOAN', 'loan_request')], default='', max_length=30),
        ),
    ]
