# Generated by Django 2.1.7 on 2019-10-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0007_offerdocument_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdocument',
            name='created',
        ),
    ]
