# Generated by Django 2.1.7 on 2019-10-10 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0009_requestdocument_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdocument',
            name='bank_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_guarantee_bank_offers_signs', to='cabinet.Certificate'),
        ),
        migrations.AlterField(
            model_name='offerdocument',
            name='client_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_guarantee_client_offers_signs', to='cabinet.Certificate'),
        ),
    ]
