# Generated by Django 2.1.7 on 2019-10-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0010_auto_20191010_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='offerdocument',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_date',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='updated_date',
            field=models.DateTimeField(verbose_name='Время последнего изменения объекта'),
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
    ]
