# Generated by Django 2.1.7 on 2019-10-16 08:35

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0012_auto_20191014_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='prepayment',
            field=models.BooleanField(default=False, verbose_name='Наличие аванса'),
        ),
        migrations.AlterField(
            model_name='request',
            name='targets',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('execution', 'На исполнение'), ('participant', 'На участие'), ('avans_return', 'Возврат аванса'), ('warranty', 'Гарантийные обязательства')], default='', max_length=200, verbose_name='Цели'),
        ),
    ]
