# Generated by Django 2.1.7 on 2019-10-15 09:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0012_auto_20191014_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='targets',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('execution', 'На исполнение'), ('participant', 'На участие'), ('avans_return', 'Возврат аванса'), ('warranty', 'Гарантийные обязательства')], default='', max_length=200, verbose_name='Цели'),
        ),
    ]
