# Generated by Django 2.1.7 on 2019-10-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0013_auto_20191015_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='prepayment',
            field=models.BooleanField(default=False, verbose_name='Наличие аванса'),
        ),
    ]
