# Generated by Django 2.1.7 on 2019-10-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0014_auto_20191015_2230'),
        ('bank_guarantee', '0013_auto_20191016_1135'),
    ]

    operations = [
    ]
