# Generated by Django 2.1.7 on 2019-10-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0014_auto_20191015_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='agent_read',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='bank_read',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='client_read',
            field=models.IntegerField(default=0),
        ),
    ]
