# Generated by Django 2.1.7 on 2019-10-20 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_guarantee', '0015_merge_20191017_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='must_read',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
