# Generated by Django 2.1.7 on 2019-10-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0015_documentlinktoperson'),
        ('bank_guarantee', '0019_auto_20191020_1732'),
    ]

    operations = [
    ]
