# Generated by Django 2.1.7 on 2019-10-21 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20191018_1301'),
        ('bank_guarantee', '0020_merge_20191020_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('text', models.TextField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Bank')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_guarantee.Request')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
