# Generated by Django 2.1.7 on 2019-10-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0015_auto_20191021_1456'),
        ('bank_guarantee', '0020_merge_20191020_2353'),
    ]

    operations = [
    ]
