# Generated by Django 2.1.7 on 2019-10-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bank_guarantee', '0022_merge_20191022_0945'),
        ('clients', '0012_auto_20191025_1904'),
    ]

    operations = [
    ]
