# Generated by Django 2.1.7 on 2019-10-28 09:15

from django.db import migrations


def rename_statuses(apps, schema_editor):
    RequestStatus = apps.get_model('bank_guarantee', 'RequestStatus')

    rename = {
        'in_bank': 'На рассмотрении в банке/МФО',
        'credit_approve': 'Одобрено банком/МФО',
        'offer_created': 'Предложение подготавливается банком/МФО',
        'bank_back': 'Предложение отозвано банком/МФО',
        'bank_send_offer': 'Банк/МФО отправил предложение',
        'request_deny': 'Заявка отклонена банком/МФО',
        'send_to_bank': 'Направлена в банк/МФО',
    }
    for key, value in rename.items():
        status = RequestStatus.objects.filter(code=key).first()
        if status:
            status.name = value
            status.save()


class Migration(migrations.Migration):
    dependencies = [
        ('bank_guarantee', '0023_auto_20191027_0329'),
    ]

    operations = [
        migrations.RunPython(rename_statuses),
    ]
