# Generated by Django 2.1.7 on 2019-11-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0024_auto_20191030_0057'),
        ('bank_guarantee', '0024_auto_20191028_1215'),
    ]

    operations = [
    ]
