# Generated by Django 2.1.7 on 2019-11-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0026_auto_20191105_1321'),
        ('bank_guarantee', '0027_merge_20191108_1233'),
    ]

    operations = [
    ]
