# Generated by Django 2.1.7 on 2019-11-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0027_merge_20191108_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
    ]
