# Generated by Django 2.1.7 on 2019-11-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0028_merge_20191108_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
    ]
