# Generated by Django 2.1.7 on 2019-11-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0028_merge_20191108_1245'),
        ('bank_guarantee', '0028_auto_20191114_1514'),
    ]

    operations = [
    ]
