# Generated by Django 2.1.7 on 2019-11-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0029_auto_20191122_1109'),
        ('bank_guarantee', '0029_merge_20191122_2240'),
    ]

    operations = [
    ]
