# Generated by Django 2.1.7 on 2020-01-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0033_auto_20200121_1139'),
        ('bank_guarantee', '0033_auto_20200121_1538'),
    ]

    operations = [
    ]
