# Generated by Django 2.1.7 on 2020-01-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0033_auto_20200121_1614'),
        ('bank_guarantee', '0034_merge_20200121_1558'),
        ('bank_guarantee', '0033_auto_20200121_1600'),
    ]

    operations = [
    ]
