# Generated by Django 2.1.7 on 2020-01-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0035_merge_20200121_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='have_additional_requirement',
            field=models.BooleanField(default=False, verbose_name='Банковская гарантия предоставляется по форме Бенефициара'),
        ),
    ]
