# Generated by Django 2.1.7 on 2020-02-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0036_auto_20200131_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatus',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Код'),
        ),
    ]
