# Generated by Django 2.1.7 on 2020-03-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0037_auto_20200221_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdocument',
            name='created',
            field=models.DateTimeField(db_index=True, editable=False),
        ),
    ]
