# Generated by Django 2.1.7 on 2020-03-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0038_auto_20200302_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdocument',
            name='old_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
