# Generated by Django 2.1.7 on 2020-03-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0040_auto_20200304_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestprintform',
            name='type',
            field=models.CharField(choices=[('', ''), ('BG', 'bank_guarantee'), ('LOAN', 'loan_request')], default='', max_length=30),
        ),
    ]
