# Generated by Django 2.1.7 on 2020-03-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0041_auto_20200306_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestprintform',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
