# Generated by Django 2.1.7 on 2020-03-16 19:06
from django.utils import timezone

from django.db import migrations


def delete_double(apps, schema_editor):
    """Удаления дубликатов"""
    Request = apps.get_model('bank_guarantee', 'Request')
    RequestDocument = apps.get_model('bank_guarantee', 'RequestDocument')
    # BaseFile = apps.get_model('files', 'BaseFile')

    for request in Request.objects.filter(
        updated_date__gte=timezone.make_aware(timezone.datetime(2020, 3, 1))):
        for doc in RequestDocument.objects.filter(request=request).iterator():
            docs = RequestDocument.objects.filter(
                request=request,
                file=doc.file,
            )
            if docs.count() > 1:
                docs.exclude(id=docs.first().id).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('bank_guarantee', '0042_auto_20200310_1431'),
        ('files', '0007_auto_20191020_1246'),
    ]

    operations = [
        migrations.RunPython(delete_double)
    ]
