# Generated by Django 2.1.7 on 2020-03-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20191020_1246'),
        ('bank_guarantee', '0043_auto_20200316_2206'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requestdocument',
            unique_together={('request', 'file')},
        ),
    ]
