# Generated by Django 2.1.7 on 2020-03-24 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0044_auto_20200317_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='bank_guarantee.Request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='discuss',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discusses', to='bank_guarantee.Request'),
        ),
        migrations.AlterField(
            model_name='message',
            name='discuss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bank_guarantee.Discuss'),
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='bank_guarantee.Message'),
        ),
    ]
