# Generated by Django 2.1.7 on 2020-03-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0045_auto_20200324_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='delivery_method',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Почта России'), (2, 'Самовывоз'), (3, 'Курьерская служба')], default=2, null=True, verbose_name='Способ доставки'),
        ),
    ]
