# Generated by Django 2.1.7 on 2020-04-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0048_auto_20200415_1646'),
        ('bank_guarantee', '0048_auto_20200416_1154'),
    ]

    operations = [
    ]
