# Generated by Django 2.1.7 on 2020-04-22 08:18

from django.db import migrations


def remove_old_print_forms(apps, schema_editor):
    print_form = apps.get_model('bank_guarantee', 'RequestPrintForm')
    print_form.objects.filter(type__in=['zip', 'zip_baikal', 'zip_metall_invest', 'zip_rus_nar_bank']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0048_auto_20200416_1154'),
    ]

    operations = [
        migrations.RunPython(remove_old_print_forms)
    ]
