# Generated by Django 2.1.7 on 2020-04-22 13:50

from django.db import migrations

def add_verification_status(apps, schema_editor):
    request_status = apps.get_model('bank_guarantee', 'RequestStatus')
    request_status.objects.get_or_create(code='verification', defaults=dict(
        name='Верификация'
    ))


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0050_change_printform_model'),
    ]

    operations = [
        migrations.RunPython(add_verification_status)
    ]
