# Generated by Django 2.1.7 on 2020-04-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0048_auto_20200415_1646'),
        ('bank_guarantee', '0052_add_status_verifier_require_more_info'),
    ]

    operations = [
    ]
