# Generated by Django 2.1.7 on 2020-04-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0050_requestedcategory_created_date'),
        ('bank_guarantee', '0053_merge_20200424_1214'),
    ]

    operations = [
    ]
