# Generated by Django 2.1.7 on 2020-04-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0055_auto_20200424_1349'),
        ('bank_guarantee', '0054_create_deny_by_verifier_status'),
    ]

    operations = [
    ]
