# Generated by Django 2.1.7 on 2020-04-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0056_auto_20200429_1603'),
        ('bank_guarantee', '0056_merge_20200429_1554'),
    ]

    operations = [
    ]
