# Generated by Django 2.1.7 on 2020-05-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0057_merge_20200430_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestprintform',
            options={'verbose_name': 'печатная форма', 'verbose_name_plural': 'печатные формы'},
        ),
    ]
