# Generated by Django 2.1.7 on 2020-05-26 08:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0043_fill_managers'),
        ('bank_guarantee', '0058_auto_20200514_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestprintform',
            name='banks',
            field=models.ManyToManyField(related_name='allowed_print_forms', to='clients.Bank'),
        ),
        migrations.AddField(
            model_name='requestprintform',
            name='need_sign',
            field=models.BooleanField(default=True, verbose_name='Подписывается клиентом'),
        ),
        migrations.AddField(
            model_name='requestprintform',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bank', 'Банк'), ('general_bank', 'Генеральный банк'), ('agent', 'Агент'), ('general_agent', 'Генеральный агент'), ('super_agent', 'Супер агент'), ('head_agent', 'Глава агент'), ('client', 'Клиент'), ('manager', 'manager'), ('mfo', 'оператор МФО'), ('verifier', 'Верификатор')], default='', max_length=200, verbose_name='Видимо для ролей'),
        ),
        migrations.AlterField(
            model_name='requestprintform',
            name='download_name',
            field=models.CharField(help_text='Используется для понятного названия файлов при скачивании документа. Поддерживает подстановки {request_id} {request_number} {client_name} {client_inn} {client_ogrn}', max_length=300),
        ),
        migrations.AlterField(
            model_name='requestprintform',
            name='type',
            field=models.CharField(choices=[('doc', 'doc'), ('html', 'html'), ('sf_agreement', 'sf_agreement'), ('sgb_excel', 'sgb_excel'), ('inbank_bg', 'inbank_bg'), ('sgb_bg', 'sgb_bg'), ('sgb_additional8', 'sgb_additional8'), ('sgb_additional81', 'sgb_additional81'), ('metall_invest_anketa', 'metall_invest_anketa'), ('metall_invest_excel', 'metall_invest_excel'), ('metall_invest_conclusion', 'metall_invest_conclusion'), ('metall_invest_beneficiars', 'metall_invest_beneficiars'), ('voronej_excel', 'voronej_excel'), ('rtbk_anketa_excel', 'rtbk_anketa_excel'), ('rtbk_guarantor_excel', 'rtbk_guarantor_excel'), ('rib_th', 'rib_th'), ('rib', 'rib'), ('moscombank_execution', 'moscombank_execution'), ('moscombank_conclusion', 'moscombank_conclusion'), ('east_excel', 'east_excel'), ('east_conclusion', 'east_conclusion'), ('moscombank_anketa', 'moscombank_anketa'), ('inbank_conclusion', 'inbank_conclusion'), ('spb_guarantee', 'spb_guarantee'), ('spb_conclusion', 'spb_conclusion'), ('spb_extradition_decision', 'spb_extradition_decision')], max_length=30),
        ),
    ]
