# Generated by Django 2.1.7 on 2020-05-26 08:04

from django.db import migrations


def fill_pf_fields(apps, schema_editor):
    """Удаления дубликатов"""
    RequestPrintForm = apps.get_model('bank_guarantee', 'RequestPrintForm')
    Bank = apps.get_model('clients', 'Bank')
    Role = apps.get_model('users', 'Role')
    for pf in RequestPrintForm.objects.iterator():
        if pf.bank:
            pf.banks.add(pf.bank)
        else:
            pf.banks.add(*Bank.objects.all())
        pf.roles = list(Role.objects.values_list('name', flat=True))
        pf.save()


class Migration(migrations.Migration):
    dependencies = [
        ('bank_guarantee', '0059_auto_20200526_1102'),
    ]

    operations = [
        migrations.RunPython(fill_pf_fields)
    ]
