# Generated by Django 2.1.7 on 2020-05-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0062_offeradditionaldatafield_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerprintform',
            name='type',
            field=models.CharField(choices=[('doc', 'doc'), ('html', 'html'), ('sf_agreement', 'sf_agreement'), ('sgb_excel', 'sgb_excel'), ('inbank_bg', 'inbank_bg'), ('sgb_bg', 'sgb_bg'), ('sgb_additional8', 'sgb_additional8'), ('sgb_additional81', 'sgb_additional81'), ('metall_invest_anketa', 'metall_invest_anketa'), ('metall_invest_excel', 'metall_invest_excel'), ('metall_invest_conclusion', 'metall_invest_conclusion'), ('metall_invest_beneficiars', 'metall_invest_beneficiars'), ('voronej_excel', 'voronej_excel'), ('rtbk_anketa_excel', 'rtbk_anketa_excel'), ('rtbk_guarantor_excel', 'rtbk_guarantor_excel'), ('rib_th', 'rib_th'), ('rib', 'rib'), ('moscombank_execution', 'moscombank_execution'), ('moscombank_conclusion', 'moscombank_conclusion'), ('east_excel', 'east_excel'), ('east_conclusion', 'east_conclusion'), ('moscombank_anketa', 'moscombank_anketa'), ('inbank_conclusion', 'inbank_conclusion'), ('spb_guarantee', 'spb_guarantee'), ('spb_conclusion', 'spb_conclusion'), ('spb_extradition_decision', 'spb_extradition_decision')], max_length=30),
        ),
    ]
