# Generated by Django 2.1.7 on 2020-06-16 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0063_auto_20200529_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdocument',
            name='print_form',
        ),
        migrations.RemoveField(
            model_name='offerprintform',
            name='bank',
        ),
        migrations.AddField(
            model_name='bankofferdocumentcategory',
            name='print_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_guarantee.OfferPrintForm'),
        ),
    ]
