# Generated by Django 2.1.7 on 2020-06-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0063_auto_20200529_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='delivery_dop_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительный телефон получателя'),
        ),
        migrations.AddField(
            model_name='request',
            name='delivery_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email получателя'),
        ),
    ]
