# Generated by Django 2.1.7 on 2020-06-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0064_auto_20200616_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerprintform',
            name='download_name',
            field=models.CharField(blank=True, help_text='Используется для понятного названия файлов при скачивании документа. Поддерживает подстановки {request_id} {request_number} {client_name} {client_inn} {client_ogrn}', max_length=300, null=True),
        ),
    ]
