# Generated by Django 2.1.7 on 2020-06-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0066_auto_20200616_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestassignedhistory',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
