# Generated by Django 2.1.7 on 2020-06-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0067_requestassignedhistory_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdocumentcategory',
            name='step',
            field=models.PositiveIntegerField(choices=[(1, 'Первый этап'), (2, 'Второй этап')]),
        ),
    ]
