# Generated by Django 2.1.7 on 2020-06-19 12:49

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0068_auto_20200617_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='additional_status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Подстатус'),
        ),
        migrations.AlterField(
            model_name='requestprintform',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bank', 'Банк'), ('general_bank', 'Генеральный банк'), ('agent', 'Агент'), ('general_agent', 'Генеральный агент'), ('super_agent', 'Супер агент'), ('head_agent', 'Глава агент'), ('client', 'Клиент'), ('manager', 'manager'), ('mfo', 'оператор МФО'), ('verifier', 'Верификатор'), ('bank_underwriter', 'Андерайтер'), ('bank_decision_maker', 'ЛПР'), ('bank_issuer', 'Выпускающий'), ('bank_common', 'Контроль')], default='', max_length=200, verbose_name='Видимо для ролей'),
        ),
    ]
