# Generated by Django 2.1.7 on 2020-06-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0069_auto_20200619_1549'),
        ('bank_guarantee', '0064_auto_20200615_1427'),
    ]

    operations = [
    ]
