# Generated by Django 2.1.7 on 2020-06-29 11:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0070_merge_20200622_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='default_commission_bank_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Стандартная комиссия, %'),
        ),
        migrations.AddField(
            model_name='offer',
            name='delta_commission_bank_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Превышение/Понижение комиссии, %'),
        ),
        migrations.AlterField(
            model_name='requestprintform',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bank', 'Банк'), ('general_bank', 'Генеральный банк'), ('agent', 'Агент'), ('general_agent', 'Генеральный агент'), ('super_agent', 'Супер агент'), ('head_agent', 'Глава агент'), ('client', 'Клиент'), ('manager', 'manager'), ('mfo', 'оператор МФО'), ('verifier', 'Верификатор'), ('bank_underwriter', 'Андерайтер'), ('bank_decision_maker', 'ЛПР'), ('bank_issuer', 'Выпускающий'), ('bank_common', 'Контроль'), ('developer', 'Разработчик')], default='', max_length=200, verbose_name='Видимо для ролей'),
        ),
    ]
