# Generated by Django 2.1.7 on 2020-07-09 08:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0048_auto_20200709_1133'),
        ('bank_guarantee', '0071_auto_20200629_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRatingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.BankRating')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_guarantee.Request')),
            ],
        ),
    ]
