# Generated by Django 2.1.7 on 2020-07-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0071_auto_20200629_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='delta_commission_bank_percent',
        ),
        migrations.AddField(
            model_name='offer',
            name='commission_bank_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Комиссия, %'),
        ),
    ]
