# Generated by Django 2.1.7 on 2020-07-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0072_bankratingresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankratingresult',
            old_name='rating',
            new_name='bank_rating',
        ),
        migrations.AddField(
            model_name='bankratingresult',
            name='finance_state',
            field=models.CharField(default='', max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankratingresult',
            name='risk_level',
            field=models.CharField(default='', max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankratingresult',
            name='score',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
