# Generated by Django 2.1.7 on 2020-07-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0073_auto_20200709_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankratingresult',
            name='rating',
            field=models.CharField(default='', max_length=56),
            preserve_default=False,
        ),
    ]
