# Generated by Django 2.1.7 on 2020-07-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0073_offer_registry_number'),
        ('bank_guarantee', '0074_bankratingresult_rating'),
    ]

    operations = [
    ]
