# Generated by Django 2.1.7 on 2020-07-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0076_auto_20200714_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcomment',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Bank'),
        ),
    ]
