# Generated by Django 2.1.7 on 2020-07-30 11:08

import base_request.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0077_auto_20200722_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPrintFormRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to=base_request.models.make_upload_file_path, verbose_name='Файл шаблона')),
                ('policy', models.TextField(verbose_name='Политика при которой сработает форма')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='bankofferdocumentcategory',
            options={'verbose_name': 'Привязка банка к категории документов предложения', 'verbose_name_plural': 'Привязки банка к категории документов предложения'},
        ),
        migrations.AlterModelOptions(
            name='offerdocumentcategory',
            options={'verbose_name': 'Категория документов предложения', 'verbose_name_plural': 'Категории документов предложения'},
        ),
        migrations.AddField(
            model_name='requestprintform',
            name='code',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestprintform',
            name='enable_rules',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bankofferdocumentcategory',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Bank', verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='bankofferdocumentcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_guarantee.OfferDocumentCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='bankofferdocumentcategory',
            name='print_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_guarantee.OfferPrintForm', verbose_name='Печатная форма'),
        ),
        migrations.AddField(
            model_name='requestprintformrule',
            name='print_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='bank_guarantee.RequestPrintForm'),
        ),
    ]
