# Generated by Django 2.1.7 on 2020-08-18 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_guarantee', '0079_auto_20200812_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifier_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
