# Generated by Django 2.1.7 on 2020-08-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0080_auto_20200818_0922'),
    ]

    operations = [

    ]
