# Generated by Django 2.1.7 on 2020-08-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0081_auto_20200821_1457'),
    ]

    operations = [
    ]
