# Generated by Django 2.1.7 on 2020-08-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0078_auto_20200817_0912'),
        ('bank_guarantee', '0081_auto_20200821_1457'),
    ]

    operations = [
    ]
