# Generated by Django 2.1.7 on 2020-08-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0082_merge_20200827_1025'),
    ]

    operations = [
    ]
