# Generated by Django 2.1.7 on 2020-09-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0082_auto_20200826_1331'),
        ('bank_guarantee', '0083_auto_20200827_1025'),
        ('bank_guarantee', '0081_auto_20200825_1011'),
    ]

    operations = [
    ]
