# Generated by Django 2.1.7 on 2020-09-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0084_merge_20200901_1256'),
        ('bank_guarantee', '0080_auto_20200824_1244'),
    ]

    operations = [
    ]
