# Generated by Django 2.1.7 on 2020-09-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0085_auto_20200901_2224'),
        ('bank_guarantee', '0086_auto_20200925_1045'),
    ]

    operations = [
    ]
