# Generated by Django 2.1.7 on 2020-10-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0093_auto_20201007_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='tmp_manager',
        ),
    ]
