# Generated by Django 2.1.7 on 2020-10-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0096_agentrewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrewards',
            name='number',
            field=models.IntegerField(default=0, max_length=250, verbose_name='Количество выданных заявок'),
        ),
        migrations.AlterField(
            model_name='agentrewards',
            name='procent',
            field=models.IntegerField(default=0, max_length=250, verbose_name='Проценты'),
        ),
    ]
