# Generated by Django 2.1.7 on 2020-10-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0097_auto_20201012_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentrewards',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agentrewards',
            name='bank',
        ),
        migrations.DeleteModel(
            name='AgentRewards',
        ),
    ]
