# Generated by Django 2.2 on 2020-11-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0101_auto_20201030_1546'),
        ('bank_guarantee', '0101_auto_20201030_1532'),
    ]

    operations = [
    ]
