# Generated by Django 2.1.7 on 2020-11-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_auto_20200601_1442'),
        ('bank_guarantee', '0103_auto_20201106_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempOfferDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.BaseFile')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_guarantee.Offer')),
                ('print_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_guarantee.OfferPrintForm')),
            ],
        ),
    ]
