# Generated by Django 2.1.7 on 2020-11-12 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0116_contractoffer__html'),
        ('bank_guarantee', '0104_tempofferdoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50)),
                ('request_number', models.CharField(max_length=50)),
                ('status_data', models.TextField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_request', to='clients.Client')),
            ],
        ),
    ]
