# Generated by Django 2.1.7 on 2020-11-12 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0105_limitrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitrequest',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Bank'),
        ),
    ]
