# Generated by Django 2.1.7 on 2020-11-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0107_request_sign_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='reduction_agent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Превышение/снижение от агента'),
        ),
        migrations.AddField(
            model_name='offer',
            name='reduction_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Снижение/корректировка за счет банка'),
        ),
    ]
