# Generated by Django 2.1.7 on 2020-11-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0108_auto_20201118_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='sign_link_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлялась ли ссылка на подписание (после верификации)'),
        ),
    ]
