# Generated by Django 2.2 on 2020-11-24 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_guarantee', '0108_auto_20201118_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedDocNameUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_docs_names', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
