# Generated by Django 2.1.7 on 2020-11-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0109_request_sign_link_sent'),
        ('bank_guarantee', '0109_requesteddocnameuser'),
    ]

    operations = [
    ]
