# Generated by Django 2.1.7 on 2020-12-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0111_auto_20201211_1133'),
        ('bank_guarantee', '0111_auto_20201210_1142'),
    ]

    operations = [
    ]
