# Generated by Django 2.1.7 on 2019-10-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20191009_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='E-mail'),
        ),
    ]
