# Generated by Django 2.1.7 on 2019-10-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20191009_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentverification',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='agentverification',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
