# Generated by Django 2.1.7 on 2019-10-16 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_client_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='manager',
        ),
        migrations.AlterField(
            model_name='agentmanager',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='clients.Agent', unique=True),
        ),
    ]
