# Generated by Django 2.1.7 on 2019-10-18 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20191016_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstopinn',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankstopinn',
            name='inn',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
