# Generated by Django 2.1.7 on 2019-10-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20191018_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banksettings',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='mfosettings',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
