# Generated by Django 2.1.7 on 2019-10-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20191025_1904'),
        ('clients', '0012_auto_20191026_0037'),
    ]

    operations = [
    ]
