# Generated by Django 2.1.7 on 2019-11-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20191025_1624'),
        ('clients', '0013_merge_20191027_1812'),
    ]

    operations = [
    ]
