# Generated by Django 2.1.7 on 2019-12-01 23:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_auto_20191105_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateChatBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template', ckeditor_uploader.fields.RichTextUploadingField(max_length=10000)),
                ('bank_code', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
