# Generated by Django 2.1.7 on 2019-12-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_templatechatbank_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatechatbank',
            name='bank_code',
        ),
    ]
