# Generated by Django 2.1.7 on 2020-02-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_templatechatmfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.AddField(
            model_name='banksettings',
            name='work_without_ecp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mfosettings',
            name='work_without_ecp',
            field=models.BooleanField(default=False),
        ),
    ]
