# Generated by Django 2.1.7 on 2020-02-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_auto_20200211_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='legal_address_city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='legal_address_index',
        ),
        migrations.RemoveField(
            model_name='company',
            name='legal_address_street',
        ),
        migrations.AddField(
            model_name='company',
            name='legal_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Юридический адрес'),
        ),
    ]
