# Generated by Django 2.1.7 on 2020-02-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_auto_20200211_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='fact_address_city',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='fact_address_index',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='fact_address_street',
        ),
        migrations.AddField(
            model_name='agent',
            name='fact_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Фактический адрес'),
        ),
    ]
