# Generated by Django 2.1.7 on 2020-03-27 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_guarantee', '0042_auto_20200310_1431'),
        ('base_request', '0010_companydocument'),
        ('clients', '0028_auto_20200313_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoscombankDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.PositiveIntegerField()),
                ('doc_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_request.BankDocumentType')),
                ('print_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_guarantee.RequestPrintForm')),
            ],
        ),
    ]
