# Generated by Django 2.1.7 on 2020-03-27 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_moscombankdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moscombankdocument',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_request.BankDocumentType'),
        ),
        migrations.AlterField(
            model_name='moscombankdocument',
            name='print_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_guarantee.RequestPrintForm'),
        ),
    ]
