# Generated by Django 2.1.7 on 2020-03-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_request', '0010_companydocument'),
        ('bank_guarantee', '0042_auto_20200310_1431'),
        ('clients', '0030_auto_20200327_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moscombankdocument',
            name='category',
        ),
        migrations.AddField(
            model_name='moscombankdocument',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='base_request.BankDocumentType'),
        ),
        migrations.RemoveField(
            model_name='moscombankdocument',
            name='print_form',
        ),
        migrations.AddField(
            model_name='moscombankdocument',
            name='print_form',
            field=models.ManyToManyField(blank=True, null=True, to='bank_guarantee.RequestPrintForm'),
        ),
    ]
