# Generated by Django 2.1.7 on 2020-03-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_auto_20200327_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='moscombankdocument',
            name='filled',
            field=models.BooleanField(default=False),
        ),
    ]
