# Generated by Django 2.1.7 on 2020-03-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0032_moscombankdocument_filled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moscombankdocument',
            old_name='filled',
            new_name='is_filled',
        ),
    ]
