# Generated by Django 2.1.7 on 2020-04-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_moscombankdocument_equal_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksettings',
            name='verification_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mfosettings',
            name='verification_enable',
            field=models.BooleanField(default=False),
        ),
    ]
