# Generated by Django 2.1.7 on 2020-04-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_moscombankdocument_equal_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoscomIntergration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date_from', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
