# Generated by Django 2.1.7 on 2020-04-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_moscomintergration'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='accept_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='accept_contract_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
