# Generated by Django 2.1.7 on 2020-04-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_auto_20200421_1716'),
        ('clients', '0036_moscomintergration'),
    ]

    operations = [
    ]
