# Generated by Django 2.1.7 on 2020-04-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0038_fill_contract_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
