# Generated by Django 2.1.7 on 2020-05-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0039_set_confirmed_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='accept_contract',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
