# Generated by Django 2.1.7 on 2020-05-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0040_auto_20200506_1433'),
        ('clients', '0037_merge_20200424_1348'),
    ]

    operations = [
    ]
