# Generated by Django 2.1.7 on 2020-05-25 14:13

from django.db import migrations


def fill_managers(apps, schema_editor):
    client_model = apps.get_model('clients', 'Client')
    agent_manager_model = apps.get_model('clients', 'AgentManager')
    for client in client_model.objects.iterator():
        new_manager = agent_manager_model.objects.filter(agent=client.agent_company).first()
        client.manager = new_manager.manager if new_manager else None
        client.save()


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0042_client_manager'),
    ]

    operations = [
        migrations.RunPython(fill_managers)
    ]
