# Generated by Django 2.1.7 on 2020-05-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0043_fill_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Отчетство')),
                ('additional_data', models.TextField(default='{}')),
                ('credit_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='clients.Bank')),
            ],
        ),
    ]
