# Generated by Django 2.1.7 on 2020-06-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_auto_20200601_1442'),
        ('clients', '0044_banksigner'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatechatbank',
            name='files',
            field=models.ManyToManyField(default=None, null=True, to='files.BaseFile'),
        ),
        migrations.AddField(
            model_name='templatechatmfo',
            name='files',
            field=models.ManyToManyField(default=None, null=True, to='files.BaseFile'),
        ),
    ]
