# Generated by Django 2.1.7 on 2020-06-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0044_banksigner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksettings',
            name='send_via_integration',
            field=models.BooleanField(default=False, verbose_name='Отправлять заявки через интеграцию'),
        ),
        migrations.AddField(
            model_name='banksettings',
            name='update_via_integration',
            field=models.BooleanField(default=False, verbose_name='Обновлять отправленные заявки через интеграцию'),
        ),
        migrations.AddField(
            model_name='mfosettings',
            name='send_via_integration',
            field=models.BooleanField(default=False, verbose_name='Отправлять заявки через интеграцию'),
        ),
        migrations.AddField(
            model_name='mfosettings',
            name='update_via_integration',
            field=models.BooleanField(default=False, verbose_name='Обновлять отправленные заявки через интеграцию'),
        ),
        migrations.AlterField(
            model_name='banksettings',
            name='enable',
            field=models.BooleanField(default=False, verbose_name='Банк принимает заявки'),
        ),
        migrations.AlterField(
            model_name='banksettings',
            name='scoring_enable',
            field=models.BooleanField(default=True, verbose_name='Проверять ли скоринг'),
        ),
        migrations.AlterField(
            model_name='mfosettings',
            name='enable',
            field=models.BooleanField(default=False, verbose_name='Банк принимает заявки'),
        ),
        migrations.AlterField(
            model_name='mfosettings',
            name='scoring_enable',
            field=models.BooleanField(default=True, verbose_name='Проверять ли скоринг'),
        ),
    ]
