# Generated by Django 2.1.7 on 2020-06-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0044_banksigner'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='your_banks',
            field=models.CharField(max_length=300, null=True, verbose_name='С какими банками работаете'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='your_city',
            field=models.CharField(max_length=300, null=True, verbose_name='Город проживания'),
        ),
    ]
