# Generated by Django 2.1.7 on 2020-06-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0045_auto_20200610_1616'),
        ('clients', '0045_auto_20200609_1436'),
    ]

    operations = [
    ]
