# Generated by Django 2.1.7 on 2020-07-28 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0045_auto_20200723_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentVerificationComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('document_date_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('document_name_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('confirmed_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('taxation_type_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('bank_account_bik_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('bank_account_bank_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('bank_account_checking_account_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('bank_account_correspondent_account_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('bank_account_address_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('fact_address_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('equal_fact_and_legal_address_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('position_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('document_for_position_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_name_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('first_name_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('middle_name_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('email_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('series_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('number_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('issued_by_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('when_issued_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_of_birth_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('place_of_birth_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('issued_code_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('accept_contract_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('accept_contract_date_comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Agent')),
            ],
        ),
    ]
