# Generated by Django 2.1.7 on 2020-07-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0045_auto_20200716_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='manager_fio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО менеджера'),
        ),
    ]
