# Generated by Django 2.1.7 on 2020-06-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0045_auto_20200619_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='our_banks',
            field=models.ManyToManyField(null=True, to='clients.Bank', verbose_name='Какие банки на платформе Тендерхелп Вам интересны'),
        ),
    ]
