# Generated by Django 2.1.7 on 2020-07-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0046_agentverificationcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentverificationcomments',
            name='full_name_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='agentverificationcomments',
            name='id_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='agentverificationcomments',
            name='inn_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='agentverificationcomments',
            name='kpp_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='agentverificationcomments',
            name='ogrn_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='agentverificationcomments',
            name='short_name_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
