# Generated by Django 2.1.7 on 2020-07-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0046_client_manager_fio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='manager_fio',
        ),
    ]
