# Generated by Django 2.1.7 on 2020-06-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0045_requestrejectionreasontemplate'),
        ('clients', '0046_merge_20200611_1430'),
    ]

    operations = [
    ]
