# Generated by Django 2.1.7 on 2020-07-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0047_auto_20200728_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentverificationcomments',
            name='active_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
