# Generated by Django 2.1.7 on 2020-07-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0047_merge_20200616_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_class', models.CharField(max_length=256)),
                ('credit_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Bank')),
            ],
        ),
        migrations.AlterField(
            model_name='agentdocumentcategory',
            name='help_text',
            field=models.TextField(blank=True, null=True, verbose_name='Всплывающая подсказка'),
        ),
        migrations.AlterField(
            model_name='mfo',
            name='code',
            field=models.CharField(choices=[('rus_micro_finance', 'rus_micro_finance'), ('simple_finance', 'simple_finance'), ('analiz_th', 'analiz_th')], max_length=20),
        ),
    ]
