# Generated by Django 2.1.7 on 2020-06-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0047_auto_20200623_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='equal_fact_and_legal_address',
            field=models.BooleanField(),
        ),
    ]
