# Generated by Django 2.1.7 on 2020-07-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0047_remove_client_manager_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='manager_fio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО менеджера'),
        ),
    ]
