# Generated by Django 2.1.7 on 2020-06-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0048_auto_20200623_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='equal_fact_and_legal_address',
            field=models.BooleanField(default=False),
        ),
    ]
