# Generated by Django 2.1.7 on 2020-07-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0048_agentverificationcomments_active_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentverificationcomments',
            name='okpto_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
