# Generated by Django 2.1.7 on 2020-07-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0048_auto_20200709_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankrating',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
