# Generated by Django 2.1.7 on 2020-06-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0049_auto_20200623_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='document_for_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Документ на основании чего'),
        ),
    ]
