# Generated by Django 2.1.7 on 2020-08-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0054_auto_20200805_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentverificationcomments',
            name='agent',
        ),
        migrations.DeleteModel(
            name='AgentVerificationComments',
        ),
    ]
