# Generated by Django 2.1.7 on 2020-07-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0055_auto_20200630_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='equal_fact',
            field=models.CharField(blank=True, default='false_value', max_length=20, null=True, verbose_name='Почтовый адрес тест'),
        ),
    ]
