# Generated by Django 2.1.7 on 2020-08-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0055_auto_20200807_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='confirmed_documents',
            field=models.BooleanField(default=None),
        ),
    ]
