# Generated by Django 2.1.7 on 2020-08-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0056_auto_20200807_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='confirmed_documents',
            field=models.IntegerField(choices=[(1, 'Подтвержден'), (2, 'В ожидании'), (3, 'Отказано')], default=2),
        ),
    ]
