# Generated by Django 2.1.7 on 2020-07-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0058_remove_agent_equal_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='equal_fact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый адрес тест'),
        ),
    ]
