# Generated by Django 2.1.7 on 2020-08-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0058_auto_20200811_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdocument',
            name='document_confirmed',
            field=models.IntegerField(default=2),
        ),
    ]
