# Generated by Django 2.1.7 on 2020-08-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0059_agentdocument_document_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentdocument',
            old_name='document_confirmed',
            new_name='document_status',
        ),
    ]
