# Generated by Django 2.1.7 on 2020-07-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0059_agent_equal_fact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='equal_fact',
            new_name='equal_fact_testtt',
        ),
    ]
