# Generated by Django 2.1.7 on 2020-08-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0060_auto_20200813_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='confirmed_documents',
        ),
    ]
