# Generated by Django 2.1.7 on 2020-07-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0060_auto_20200702_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='equal_fact_testtt',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='equal_fact_testtt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый адрес тест'),
        ),
    ]
