# Generated by Django 2.1.7 on 2020-07-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0061_auto_20200702_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='equal_fact_testtt',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='equal_fact_crutch',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый адрес отличается от юридического Костыль'),
        ),
    ]
