# Generated by Django 2.1.7 on 2020-08-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0063_auto_20200814_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='confirmed_documents',
        ),
    ]
