# Generated by Django 2.1.7 on 2020-07-03 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0067_auto_20200703_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='our_banks',
        ),
    ]
