# Generated by Django 2.1.7 on 2020-07-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0071_agentprofile_our_banks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='our_banks',
        ),
    ]
