# Generated by Django 2.1.7 on 2020-07-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0075_auto_20200703_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowClients_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='our_banks',
            field=models.ManyToManyField(null=True, to='clients.HowClients_test', verbose_name='Какие банки на платформе Тендерхелп Вам интересны'),
        ),
    ]
