# Generated by Django 2.1.7 on 2020-07-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0077_auto_20200703_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HowClients_test',
        ),
    ]
