# Generated by Django 2.1.7 on 2020-07-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0078_delete_howclients_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='your_city',
            field=models.CharField(max_length=300, null=True, verbose_name='Город проживания'),
        ),
    ]
