# Generated by Django 2.1.7 on 2020-07-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0079_auto_20200707_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='experience',
            field=models.CharField(max_length=15, null=True, verbose_name='Опыт работы агентом'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='your_banks',
            field=models.CharField(max_length=300, null=True, verbose_name='С какими банками работаете'),
        ),
    ]
