# Generated by Django 2.1.7 on 2020-07-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0081_auto_20200707_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='priority_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Какие условия считаете приоритетными в работе'),
        ),
    ]
