# Generated by Django 2.1.7 on 2020-07-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0082_auto_20200707_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='our_banks',
        ),
    ]
