# Generated by Django 2.1.7 on 2020-07-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0083_remove_agentprofile_our_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='our_banks',
            field=models.ManyToManyField(blank=True, null=True, to='clients.Bank', verbose_name='Какие банки на платформе Тендерхелп Вам интересны'),
        ),
    ]
