# Generated by Django 2.1.7 on 2020-07-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0047_merge_20200616_1610'),
        ('clients', '0084_agentprofile_our_banks'),
    ]

    operations = [
    ]
