# Generated by Django 2.1.7 on 2020-07-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0086_auto_20200709_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Опыт работы агентом'),
        ),
    ]
