# Generated by Django 2.1.7 on 2020-07-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0087_auto_20200709_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='fill_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='fill_requisites',
            field=models.BooleanField(default=False),
        ),
    ]
