# Generated by Django 2.1.7 on 2020-07-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0088_auto_20200710_1232'),
        ('clients', '0045_auto_20200715_1230'),
        ('clients', '0049_bankrating_active'),
    ]

    operations = [
    ]
