# Generated by Django 2.1.7 on 2020-07-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0048_client_manager_fio'),
        ('clients', '0089_merge_20200714_1550'),
    ]

    operations = [
    ]
