# Generated by Django 2.1.7 on 2020-07-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0089_merge_20200721_1046'),
        ('clients', '0090_merge_20200721_1813'),
    ]

    operations = [
    ]
