# Generated by Django 2.1.7 on 2020-08-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0090_merge_20200721_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='fill_requisites',
        ),
    ]
