# Generated by Django 2.1.7 on 2020-07-28 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0091_merge_20200722_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalnews',
            options={'verbose_name': 'Новость в кабинетах', 'verbose_name_plural': 'Новости в кабинетах'},
        ),
        migrations.AlterField(
            model_name='bankrating',
            name='credit_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Bank'),
        ),
    ]
