# Generated by Django 2.1.7 on 2020-08-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0091_merge_20200722_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalnews',
            options={'verbose_name': 'Новость в кабинетах', 'verbose_name_plural': 'Новости в кабинетах'},
        ),
        migrations.RemoveField(
            model_name='agent',
            name='fill_requisites',
        ),
    ]
