# Generated by Django 2.1.7 on 2020-08-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0091_merge_20200722_1228'),
        ('clients', '0092_agent_fill_requisites'),
    ]

    operations = [
    ]
