# Generated by Django 2.1.7 on 2020-08-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0092_auto_20200728_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='how_clients',
            field=models.ManyToManyField(blank=True, to='clients.HowClients', verbose_name='С какими клиентами работаете'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='our_banks',
            field=models.ManyToManyField(blank=True, to='clients.Bank', verbose_name='Какие банки на платформе Тендерхелп Вам интересны'),
        ),
        migrations.AlterField(
            model_name='moscombankdocument',
            name='category',
            field=models.ManyToManyField(blank=True, to='base_request.BankDocumentType'),
        ),
        migrations.AlterField(
            model_name='moscombankdocument',
            name='print_form',
            field=models.ManyToManyField(blank=True, to='bank_guarantee.RequestPrintForm'),
        ),
        migrations.AlterField(
            model_name='templatechatbank',
            name='files',
            field=models.ManyToManyField(default=None, to='files.BaseFile'),
        ),
        migrations.AlterField(
            model_name='templatechatmfo',
            name='files',
            field=models.ManyToManyField(default=None, to='files.BaseFile'),
        ),
    ]
