# Generated by Django 2.1.7 on 2020-08-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0093_auto_20200812_1618'),
        ('clients', '0093_merge_20200827_1106'),
    ]

    operations = [
    ]
