# Generated by Django 2.1.7 on 2020-08-27 21:40

from django.db import migrations, models


def init_client_change_agent_history(apps, schema_editor):
    ClientChangeAgentHistory = apps.get_model('clients', 'ClientChangeAgentHistory')
    Client = apps.get_model('clients', 'Client')
    for client in Client.objects.all():
        if client.agent_company and client.agent_user:
            ClientChangeAgentHistory.objects.create(
                agent_company=client.agent_company,
                agent_user=client.agent_user,
                client=client
            )


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0093_auto_20200812_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientchangeagenthistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunPython(init_client_change_agent_history)
    ]
