# Generated by Django 2.1.7 on 2020-08-17 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_auto_20200601_1442'),
        ('clients', '0093_agent_fill_requisites'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionsDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название докумнета')),
                ('name2', models.CharField(max_length=255, verbose_name='Название документа в кабинете')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('show', models.BooleanField(default=True, verbose_name='Отображение в кабинете')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.BaseFile')),
            ],
        ),
    ]
