# Generated by Django 2.1.7 on 2020-08-27 23:54

from django.db import migrations


def init_last_action(apps, schema_editor):
    RequestHistory = apps.get_model('bank_guarantee', 'RequestHistory')
    Client = apps.get_model('clients', 'Client')
    for client in Client.objects.all():
        history = RequestHistory.objects.filter(user__client_id=client).last()
        if history:
            client.date_last_action = history.created.date()
            client.save()


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0094_auto_20200828_0040'),
        ('bank_guarantee', '0081_auto_20200821_1457')
    ]

    operations = [
        migrations.RunPython(init_last_action)
    ]
