# Generated by Django 2.1.7 on 2020-08-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_auto_20200601_1442'),
        ('clients', '0094_instructionsdocuments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstructionsDocuments',
            new_name='AgentInstructionsDocuments',
        ),
    ]
