# Generated by Django 2.1.7 on 2020-08-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0094_merge_20200826_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='fill_requisites',
        ),
    ]
