# Generated by Django 2.1.7 on 2020-08-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0095_remove_agent_fill_requisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='fill_requisites',
            field=models.BooleanField(default=False),
        ),
    ]
