# Generated by Django 2.1.7 on 2020-08-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0093_auto_20200812_1618'),
        ('clients', '0097_auto_20200819_0937'),
    ]

    operations = [
    ]
