# Generated by Django 2.1.7 on 2020-09-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0096_agent_fill_requisites'),
        ('clients', '0095_auto_20200825_1036'),
        ('clients', '0095_auto_20200828_0254'),
        ('clients', '0098_merge_20200827_1025'),
    ]

    operations = [
    ]
