# Generated by Django 2.1.7 on 2020-09-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0094_merge_20200827_1145'),
        ('clients', '0099_merge_20200901_1249'),
    ]

    operations = [
    ]
