# Generated by Django 2.1.7 on 2020-09-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0100_merge_20200901_1406'),
        ('clients', '0094_merge_20200817_1742'),
    ]

    operations = [
    ]
