# Generated by Django 2.1.7 on 2020-10-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0104_auto_20201001_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksettings',
            name='hide_user_names',
            field=models.BooleanField(default=False, verbose_name='Скрыть ФИО сотрудников в чате'),
        ),
        migrations.AddField(
            model_name='mfosettings',
            name='hide_user_names',
            field=models.BooleanField(default=False, verbose_name='Скрыть ФИО сотрудников в чате'),
        ),
    ]
