# Generated by Django 2.1.7 on 2020-10-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0105_agentrewards'),
    ]

    operations = [
    ]
