# Generated by Django 2.1.7 on 2020-10-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0107_auto_20201013_1014'),
    ]

    operations = [

    ]
