# Generated by Django 2.1.7 on 2020-10-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0105_auto_20201007_1006'),
        ('clients', '0108_auto_20201014_0913'),
    ]

    operations = [
    ]
