# Generated by Django 2.2 on 2020-10-30 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_auto_20200601_1442'),
        ('clients', '0111_auto_20201027_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='accept_contract',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='accept_contract_date',
        ),
        migrations.CreateModel(
            name='ContractOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала действия')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.BaseFile', verbose_name='Договор-оферта')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='AgentContractOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_date', models.DateTimeField(verbose_name='Дата принятия договора')),
                ('accept_contract', models.BooleanField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Agent')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.ContractOffer', verbose_name='Договор')),
            ],
        ),
    ]
