# Generated by Django 2.2 on 2020-10-30 13:08

from django.db import migrations
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0113_auto_20201030_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractoffer',
            name='file',
            field=files.models.ExtendedFileField(upload_to='contract_offer/%Y-%m-%d/', verbose_name='Договор'),
        ),
    ]
