# Generated by Django 2.2 on 2020-10-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0114_auto_20201030_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcontractoffer',
            name='accept_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия договора'),
        ),
    ]
