# Generated by Django 2.2 on 2020-11-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0115_auto_20201030_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoffer',
            name='_html',
            field=models.TextField(default='Сотрудничество с компанией Тендерхелп действует на основании \n        публичной оферты, размещённой по <a target="_blank" \n        href="HREF">ссылке</a> и в разделе <a \n        href="https://tenderhelp.ru/docs">https://tenderhelp.ru/docs</a>. <br> ', verbose_name='Текст модального окна'),
        ),
    ]
