# Generated by Django 2.2 on 2020-11-27 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0118_auto_20201116_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoffer',
            name='accept_text',
            field=models.CharField(default='Принять', max_length=50, verbose_name='Текст кнопки принятия'),
        ),
        migrations.AddField(
            model_name='contractoffer',
            name='cancel_text',
            field=models.CharField(default='Отказ', max_length=50, verbose_name='Текст кнопки отказа'),
        ),
        migrations.AddField(
            model_name='contractoffer',
            name='help_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contractoffer',
            name='replaced',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.ContractOffer', verbose_name='Заменён'),
        ),
        migrations.AddField(
            model_name='contractoffer',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Обязательность принятия'),
        ),
        migrations.AddField(
            model_name='contractoffer',
            name='Нзавание документа',
            field=models.CharField(default='Регламент', max_length=300),
        ),
    ]
