# Generated by Django 2.2 on 2020-11-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0119_auto_20201127_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractoffer',
            name='help_text',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
