# Generated by Django 2.2 on 2020-11-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0121_auto_20201127_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractoffer',
            name='Нзавание документа',
        ),
        migrations.AddField(
            model_name='contractoffer',
            name='name',
            field=models.CharField(default='Регламент', max_length=300, verbose_name='Нзавание документа'),
        ),
    ]
