# Generated by Django 2.1.7 on 2020-12-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0122_auto_20201130_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinstructionsdocuments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='instructions/%Y-%m-%d/'),
        ),
    ]
