# Generated by Django 2.2 on 2020-12-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0123_auto_20201204_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractoffer',
            name='_html',
            field=models.TextField(default='Сотрудничество с компанией Тендерхелп действует на основании \n        публичной оферты, размещённой по <a target="_blank" \n        href="HREF">ссылке</a> и в разделе <a \n        href="https://tenderhelp.ru/docs">https://tenderhelp.ru/docs</a>. <br>\n         <br>Прежде, чем выразить согласие, ознакомьтесь с\n            условиями договора. <br>', verbose_name='Текст модального окна'),
        ),
    ]
