# Generated by Django 2.2 on 2020-12-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0124_auto_20201211_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksettings',
            name='archive_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Через сколько дней отправлять в архив'),
        ),
        migrations.AddField(
            model_name='mfosettings',
            name='archive_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Через сколько дней отправлять в архив'),
        ),
    ]
