# Generated by Django 2.1.7 on 2019-10-09 06:32

import django.core.validators
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='0', max_length=255, verbose_name='Название организации')),
                ('fio', models.CharField(default='0', max_length=255, verbose_name='Фамилия, имя и отчество')),
                ('number', models.CharField(default=0, max_length=255)),
                ('date_granted', models.CharField(max_length=50, verbose_name='Дата выдачи сертификата')),
                ('date_end', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата окончания сертификата')),
                ('subject_name', models.CharField(max_length=500, verbose_name='Полная строка SubjectName')),
                ('issuer_name', models.CharField(max_length=500, verbose_name='Полная строка IssuerName')),
                ('algorithm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Алгоритм')),
                ('export', models.TextField(blank=True, verbose_name='Base64 данные открытого ключа')),
                ('uc', models.CharField(blank=True, max_length=500, verbose_name='Издатель')),
            ],
            options={
                'verbose_name': 'Сертификаты',
                'verbose_name_plural': 'Сертификат',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CertifyingCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, validators=[utils.validators.validate_inn], verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Список удостоверяющих центров',
                'verbose_name_plural': 'Удостоверяющий центр',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EgrulData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=20)),
                ('data', models.TextField(blank=True, default='{}', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Организационно-правовая форма',
                'verbose_name_plural': 'Организационно-правовые формы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PlacementPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название площадки')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код площадки, которая является основной')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код площадки - только для базовых площадок')),
            ],
            options={
                'verbose_name': 'Площадка размещения',
                'verbose_name_plural': 'Площадки размещения',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_date', models.DateTimeField(auto_now_add=True)),
                ('sign', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_on', models.BooleanField(default=True)),
                ('scoring_on', models.IntegerField(default=True)),
                ('auto_save', models.PositiveIntegerField(default=500)),
                ('strong_check', models.BooleanField(default=True)),
                ('inn_check', models.BooleanField(default=True)),
                ('cnt_right', models.BooleanField(default=True)),
                ('archive_days', models.PositiveIntegerField(default=30)),
                ('bank_stop_inn', models.BooleanField(default=True)),
                ('global_stop_inn', models.BooleanField(default=True)),
                ('algorithm', models.BooleanField(default=True)),
                ('ogrn', models.BooleanField(default=True)),
                ('subject_sign_tool', models.BooleanField(default=False)),
                ('issuer_sign_tool', models.BooleanField(default=False)),
                ('certificate_policies', models.BooleanField(default=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('check_profile', models.IntegerField(blank=True, null=True)),
                ('limit_file_size', models.DecimalField(decimal_places=1, default=40, max_digits=4)),
                ('static_pages', models.TextField()),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('admin_email', models.CharField(max_length=255)),
                ('email_support', models.CharField(max_length=2000)),
                ('email_calculator', models.CharField(max_length=2000)),
                ('email_callback', models.CharField(max_length=2000)),
                ('agents_counter', models.PositiveIntegerField(default=0)),
                ('msp_notify', models.CharField(max_length=2000)),
                ('validate_sign', models.BooleanField(default=True)),
                ('request_number', models.PositiveIntegerField(blank=True, null=True)),
                ('cert_valid', models.BooleanField(default=True)),
                ('tenderhelp_loan_offer_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TaxSystems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Система налогообложения',
                'verbose_name_plural': 'Системы налогообложения',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bg_type', models.CharField(choices=[('execution', 'На исполнение'), ('participant', 'На участие'), ('avans_return', 'Возврат аванса'), ('warranty', 'Гарантийные обязательства')], max_length=30)),
                ('limit_from', models.PositiveIntegerField()),
                ('limit_to', models.PositiveIntegerField()),
                ('commission', models.FloatField()),
                ('commission_on_excess', models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
