# Generated by Django 2.1.7 on 2019-10-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_auto_20191009_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
