# Generated by Django 2.1.7 on 2020-01-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_system_default_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='admin_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='system',
            name='auto_save',
            field=models.PositiveIntegerField(default=500, verbose_name='Время автосохранения анкеты'),
        ),
        migrations.AlterField(
            model_name='system',
            name='email_calculator',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='system',
            name='email_callback',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='system',
            name='email_support',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='system',
            name='msp_notify',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='system',
            name='scoring_on',
            field=models.IntegerField(default=True, verbose_name='Прием заявок включен'),
        ),
        migrations.AlterField(
            model_name='system',
            name='site_on',
            field=models.BooleanField(default=True, verbose_name='Доступ в личные кабинеты открыт'),
        ),
        migrations.AlterField(
            model_name='system',
            name='static_pages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
