# Generated by Django 2.1.7 on 2020-01-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_auto_20200121_1600'),
        ('cabinet', '0007_auto_20200121_1614'),
    ]

    operations = [
    ]
