# Generated by Django 2.1.7 on 2020-02-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0008_merge_20200121_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='algorithm',
            field=models.BooleanField(default=True, verbose_name='УКЭП: Алгоритм подписи сертификата ГОСТ Р 34.11-94/34.10-2001 (1.2.643.2.2.3)'),
        ),
        migrations.AlterField(
            model_name='system',
            name='cert_valid',
            field=models.BooleanField(default=True, verbose_name='Проверка валидности сертификата на сайте ГосУслуги'),
        ),
        migrations.AlterField(
            model_name='system',
            name='certificate_policies',
            field=models.BooleanField(default=True, verbose_name='УКЭП: Наличие дополнения CertificatePolicies (2.5.29.32)'),
        ),
        migrations.AlterField(
            model_name='system',
            name='inn_check',
            field=models.BooleanField(default=True, verbose_name='УКЭП: Наличие ИНН УЦ в xml-списке e-trust.gosuslugi.ru'),
        ),
        migrations.AlterField(
            model_name='system',
            name='issuer_sign_tool',
            field=models.BooleanField(default=False, verbose_name='УКЭП: Наличие дополнения IssuerSignTool (1.2.643.100.112)'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ogrn',
            field=models.BooleanField(default=True, verbose_name="УКЭП: Наличие атрибута ОГРН в поле 'Issuer'"),
        ),
        migrations.AlterField(
            model_name='system',
            name='strong_check',
            field=models.BooleanField(default=True, verbose_name='УКЭП: Осуществлять проверку на соответствие УКЭП'),
        ),
        migrations.AlterField(
            model_name='system',
            name='subject_sign_tool',
            field=models.BooleanField(default=False, verbose_name='УКЭП: Наличие дополнения SubjectSignTool (1.2.643.100.111)'),
        ),
        migrations.AlterField(
            model_name='system',
            name='uc',
            field=models.BooleanField(default=True, verbose_name='Проверка центра выдавщего сертификат'),
        ),
        migrations.AlterField(
            model_name='system',
            name='validate_sign',
            field=models.BooleanField(default=True, verbose_name='Проверка корректности подписи на стороне сервера'),
        ),
    ]
