# Generated by Django 2.1.7 on 2020-03-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0012_system_one_package_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrule',
            name='limit_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workrule',
            name='limit_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
