# Generated by Django 2.1.7 on 2020-03-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0013_auto_20200320_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='default_scoring_rules',
            field=models.TextField(default='[]'),
        ),
    ]
