# Generated by Django 2.1.7 on 2020-03-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0014_system_default_scoring_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrule',
            name='commission_on_excess',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
