# Generated by Django 2.1.7 on 2020-04-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0016_system_email_new_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issuer_name',
            field=models.CharField(max_length=1000, verbose_name='Полная строка IssuerName'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='subject_name',
            field=models.CharField(max_length=1000, verbose_name='Полная строка SubjectName'),
        ),
    ]
