DOCUMENTS = {
    'doc_egrulExtract': {
        'isMultiple': False,
        'docName': 'Выписка из ЕГРЮЛ'}, 'doc_reissueReason': {
        'isMultiple': False,
        'docName': 'Обоснование изменения формы гарантии'},
    'doc_managingCompany': {'isMultiple': False,
                            'docName': 'Договор с Управляющей компанией'},
    'doc_bkiPermission': {'isMultiple': False,
                          'docName': 'Согласие на получение кредитной истории в БКИ'},
    'doc_principalCharter': {'isMultiple': False, 'docName': 'Устав принципала'},
    'doc_bill': {'isMultiple': False,
                 'docName': 'Предложение условий выдачи банковской гарантии и Счет на оплату вознаграждения за выдачу банковской гарантии'},
    'doc_companyBuhScanPdfWithoutBarcode': {'isMultiple': False,
                                            'docName': 'Скан бух отчетности'},
    'doc_persDataAgree': {'isMultiple': False,
                          'docName': 'Согласие на обработку персональных данных'},
    'doc_finReportConfirm': {'isMultiple': True,
                             'docName': 'Подтверждение отправки годовой отчетности'},
    'doc_benLetter': {'isMultiple': True,
                      'docName': 'Письмо от Бенефициара об отсутствии претензий к Принципалу по выполняемому контракту с указанием объема выполненных работ'},
    'doc_guarantorDocumentEIO': {'isMultiple': True,
                                 'docName': 'Документ, удостоверяющий личность Генерального директора или представителя Клиента, действующего по доверенности. Обязателен при формировании заявки.'},
    'doc_comDecreaseReason': {'isMultiple': False,
                              'docName': 'Обоснование понижения комиссии'},
    'doc_woApp': {'isMultiple': False,
                  'docName': 'Справка об отсутствии необходимости одобрения сделки'},
    'doc_otherClientDocs': {'isMultiple': True, 'docName': 'Прочие документы'},
    'doc_credDecision': {'isMultiple': False, 'docName': 'Кредитное решение'},
    'doc_principalConfirmingSigner': {'isMultiple': False,
                                      'docName': 'Документ, подтверждающий право подписи'},
    'doc_bgScan': {'isMultiple': False,
                   'docName': 'Сканированная копия банковской гарантии'},
    'doc_principalPassport': {'isMultiple': True,
                              'docName': 'Паспорта ФЛ. Обязателен при формировании заявки.'},
    'doc_bigDealApprove': {'isMultiple': False,
                           'docName': 'Решение уполномоченного органа об одобрении крупной сделки'},
    'doc_principalDocumentConfirming': {'isMultiple': True,
                                        'docName': 'Документ, подтверждающий право собственности или аренды помещения. Обязателен при формировании заявки. '},
    'doc_bgReissued': {'isMultiple': False, 'docName': 'Гарантия (изменённая)'},
    'doc_taxForm': {'isMultiple': True,
                    'docName': 'Налоговая декларация за отчетный период с отметкой о принятии или заверенная ЭЦП налоговым органом или копией почтовой квитанции. Обязателен при формировании заявки.'},
    'doc_visa': {'isMultiple': True, 'docName': 'Сведения о въездной визе'},
    'doc_Nonresident': {'isMultiple': True,
                        'docName': 'Документ, подтверждающий право иностранного гражданина или лица без гражданства на пребывание (проживание) в РФ'},
    'doc_agentBillingAct': {'isMultiple': False, 'docName': 'Акт биллинга агента'},
    'doc_requestGuarantee': {'isMultiple': False,
                             'docName': 'Подписанный скан заявления на выдачу банковской гарантии'},
    'doc_edoAgree': {'isMultiple': False,
                     'docName': 'Согласие с присоединением к Регламенту ЭДО'},
    'doc_accessionRequest': {'isMultiple': False,
                             'docName': 'Заявление о присоединении к Договору'},
    'doc_otherRisks': {'isMultiple': True, 'docName': 'Прочие документы ДКР'},
    'doc_principalLicense': {'isMultiple': True,
                             'docName': 'Лицензии. Обязателен при формировании заявки.'},
    'doc_otherFins': {'isMultiple': True, 'docName': 'Прочие финансовые документы'},
    'doc_debtStatement': {'isMultiple': False,
                          'docName': 'Справка о задолженности из налогового органа'},
    'doc_companyBuhScanPdfXml': {'isMultiple': False,
                                 'docName': 'Контейнер ФНС (бух отчетность)'},
    'doc_executedContracts': {'isMultiple': True,
                              'docName': 'Исполненный(ые) контракт(ы) и подписанный(ые) акт(ы) приема-передачи товаров (выполнения работ, оказания услуг)'},
    'doc_principalExtractRegistry': {'isMultiple': False,
                                     'docName': 'Выписка из реестра акционеров. Обязателен при формировании заявки.'},
    'doc_principalCharterChange': {'isMultiple': False,
                                   'docName': 'Изменение устава принципала'},
    'doc_guarantee': {'isMultiple': False, 'docName': 'Гарантия'},
    'doc_finReportQ': {'isMultiple': True,
                       'docName': 'Бухгалтерская отчетность - бухгалтерский баланс и отчет о прибылях и убытках последний квартал. Обязателен при формировании заявки.'},
    'doc_formManagingComp': {'isMultiple': False,
                             'docName': 'Анкета управляющей компании'},
    'doc_companyBuhScanPdfWithBarcode': {'isMultiple': False,
                                         'docName': 'Скан бух отчетности (pdf417)'},
    'doc_purchase': {'isMultiple': True, 'docName': 'Документация о закупке'},
    'doc_principalDocumentEIO': {'isMultiple': False,
                                 'docName': 'Документ о назначении единоличного исполнительного органа Клиента (протокол/решение об избрании/назначении, приказ о назначении). Обязателен при формировании заявки.'},
    'doc_guaranteeContract': {'isMultiple': False, 'docName': 'Гарантийниый договор'},
    'doc_orderComments': {'isMultiple': False, 'docName': 'Переписка по сделке'},
    'doc_accountArrests': {'isMultiple': False,
                           'docName': 'Отчет о результате запроса о действующих решениях ФНС о приостановлении операций по счетам Клиента в банках (копия экрана)'},
    'doc_principalFinReport': {'isMultiple': True,
                               'docName': 'Бухгалтерская отчётность. Обязателен при формировании заявки.'},
    'doc_boardElect': {'isMultiple': False,
                       'docName': 'Протокол об избрании совета директоров (наблюдательного совета)'},
    'doc_principalForm': {'isMultiple': False, 'docName': 'Анкета клиента'},
    'doc_profVerdict': {'isMultiple': False, 'docName': 'Профессиональное суждение'},
    'doc_bgReissuedScan': {'isMultiple': False,
                           'docName': 'Скан оригинала гарантии (изменённой)'}}

